version: "3.9"
services:
  postgres:
    image: postgres:16-alpine
    container_name: vnspeech-pg
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vn_speech_guardian
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: vnspeech-adminer
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  pg_data: