version: "3.9"
services:
  postgres:
    image: postgres:16-alpine
    container_name: vsg-postgres
    environment:
      POSTGRES_USER: vsg
      POSTGRES_PASSWORD: vsg
      POSTGRES_DB: vsg_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer:4.8.1
    container_name: vsg-adminer
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data: